FORMAT: 1A
HOST: https://api.tripguru.com

All parameters called UUID are implementations of [RFC4122](http://www.ietf.org/rfc/rfc4122.txt)

Responses are compliant with JSON-API)[http://jsonapi.org/] standard.

<!-- include(common_data_structures.apib) -->

<!-- include(tour/docs.apib) -->


